management:
  context-path: /diagnostics

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: mifinity
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  datasource:
    url: jdbc:h2:mem:mifinity;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS mifinity\;SET SCHEMA mifinity
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-test-query: select 1
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

cors:
  allowedOrigins:
    - "http://localhost:4200"
    - "*"
  allowedMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowedHeaders:
    - "Authorization"
    - "Content-Type"
    - "x-xsrf-token"